using VerifyCS = Ling.AutoInject.SourceGenerators.Tests.Verifiers.CSharpSourceGeneratorVerifier<
    Ling.AutoInject.SourceGenerators.AutoInjectGenerator>;

namespace Ling.AutoInject.SourceGenerators.Tests;

public class AutoInjectGeneratorTests
{
    [Fact]
    public async Task RecordClass_GeneratesRegistration()
    {
        const string source = """
            using Ling.AutoInject;

            namespace Test;

            [ScopedService]
            public sealed record MyService;
            """;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices: string.Empty,
            expectedScopedServices: "services.TryAddScoped<global::Test.MyService>();",
            expectedTransientServices: string.Empty);
    }

    private static async Task VerifyGeneratedCodeAsync(string source, string expectedGeneratedCode)
    {
        await VerifyCS.VerifySourceGeneratorAsync(
            source,
            ("AutoInjectConfigAttribute.g.cs", SourceCodes.AutoInjectConfigAttribute),
            ("AutoInjectExtensionsAttribute.g.cs", SourceCodes.AutoInjectExtensionsAttribute),
            ("AutoInjectAttribute.g.cs", SourceCodes.AutoInjectAttribute),
#if NET8_0_OR_GREATER
            ("AutoInjectKeyedRegistration.g.cs", SourceCodes.KeyedRegistration),
#endif
            ("SingletonServiceAttribute.g.cs", SourceCodes.SingletonServiceAttribute),
            ("ScopedServiceAttribute.g.cs", SourceCodes.ScopedServiceAttribute),
            ("TransientServiceAttribute.g.cs", SourceCodes.TransientServiceAttribute),
            ("AutoInject_TestProject.g.cs", expectedGeneratedCode));
    }

    private static async Task VerifyGeneratedCodeAsync(
        string source,
        string? expectedSingletonServices,
        string? expectedScopedServices,
        string? expectedTransientServices)
    {
        static string IndentServiceLines(string? serviceLines) => string.IsNullOrWhiteSpace(serviceLines)
                ? string.Empty
                : string.Concat(serviceLines.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None).Select(line => Environment.NewLine + "            " + line.Trim()));

        var singletonServicesBody = IndentServiceLines(expectedSingletonServices);
        var scopedServicesBody = IndentServiceLines(expectedScopedServices);
        var transientServicesBody = IndentServiceLines(expectedTransientServices);

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;

            namespace TestProject
            {
                /// <summary>
                /// Auto-generated extension methods for registering services with AutoInject attributes.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static partial class TestProject_AutoInjectGenerated
                {
                    /// <summary>
                    /// Adds services decorated with AutoInject attributes from the assembly 'TestProject' to the IServiceCollection.
                    /// <para>
                    /// Implements the 'AddAdditionalServices' partial method to further customize service registrations.
                    /// </para>
                    /// </summary>
                    /// <param name="services">The IServiceCollection to add services to.</param>
                    /// <returns>The IServiceCollection for chaining.</returns>
                    public static IServiceCollection AddTestProjectServices(this IServiceCollection services)
                    {
                        if (services == null) throw new global::System.ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);
                        AddAdditionalServices(services);

                        return services;
                    }

                    private static void AddSingletonServices(IServiceCollection services)
                    {{{singletonServicesBody}}
                    }

                    private static void AddScopedServices(IServiceCollection services)
                    {{{scopedServicesBody}}
                    }
 
                    private static void AddTransientServices(IServiceCollection services)
                    {{{transientServicesBody}}
                    }

                    /// <summary>
                    /// Adds additional services to the container.
                    /// </summary>
                    /// <param name="services">The service collection.</param>
                    static partial void AddAdditionalServices(IServiceCollection services);
                }
            }

            """;

        await VerifyCS.VerifySourceGeneratorAsync(
            source,
            ("AutoInjectConfigAttribute.g.cs", SourceCodes.AutoInjectConfigAttribute),
            ("AutoInjectExtensionsAttribute.g.cs", SourceCodes.AutoInjectExtensionsAttribute),
            ("AutoInjectAttribute.g.cs", SourceCodes.AutoInjectAttribute),
#if NET8_0_OR_GREATER
            ("AutoInjectKeyedRegistration.g.cs", SourceCodes.KeyedRegistration),
#endif
            ("SingletonServiceAttribute.g.cs", SourceCodes.SingletonServiceAttribute),
            ("ScopedServiceAttribute.g.cs", SourceCodes.ScopedServiceAttribute),
            ("TransientServiceAttribute.g.cs", SourceCodes.TransientServiceAttribute),
            ("AutoInject_TestProject.g.cs", generatedCode));
    }

    [Fact]
    public async Task WithCustomMethod_GeneratesExtensionClass()
    {
        const string source = """
            [assembly: Ling.AutoInject.AutoInjectConfig(MethodName = "AddCustomServices", ClassName = "ServiceExtensions", Namespace = "MyNamespace")]
            """;
        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;

            namespace MyNamespace
            {
                /// <summary>
                /// Auto-generated extension methods for registering services with AutoInject attributes.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static partial class ServiceExtensions
                {
                    /// <summary>
                    /// Adds services decorated with AutoInject attributes from the assembly 'TestProject' to the IServiceCollection.
                    /// <para>
                    /// Implements the 'AddAdditionalServices' partial method to further customize service registrations.
                    /// </para>
                    /// </summary>
                    /// <param name="services">The IServiceCollection to add services to.</param>
                    /// <returns>The IServiceCollection for chaining.</returns>
                    public static IServiceCollection AddCustomServices(this IServiceCollection services)
                    {
                        if (services == null) throw new global::System.ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);
                        AddAdditionalServices(services);

                        return services;
                    }

                    private static void AddSingletonServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddScopedServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddTransientServices(IServiceCollection services)
                    {
                    }

                    /// <summary>
                    /// Adds additional services to the container.
                    /// </summary>
                    /// <param name="services">The service collection.</param>
                    static partial void AddAdditionalServices(IServiceCollection services);
                }
            }

            """;
        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Fact]
    public async Task WithPartialClass_GeneratesExtensionClass()
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                [AutoInjectExtensions(MethodName = "AddCustomServices")]
                public static partial class MyServiceExtensions { }
            }
            """;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;

            namespace Test
            {
                /// <summary>
                /// Auto-generated extension methods for registering services with AutoInject attributes.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                static partial class MyServiceExtensions
                {
                    /// <summary>
                    /// Adds services decorated with AutoInject attributes from the assembly 'TestProject' to the IServiceCollection.
                    /// <para>
                    /// Implements the 'AddAdditionalServices' partial method to further customize service registrations.
                    /// </para>
                    /// </summary>
                    /// <param name="services">The IServiceCollection to add services to.</param>
                    /// <returns>The IServiceCollection for chaining.</returns>
                    public static IServiceCollection AddCustomServices(this IServiceCollection services)
                    {
                        if (services == null) throw new global::System.ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);
                        AddAdditionalServices(services);

                        return services;
                    }

                    private static void AddSingletonServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddScopedServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddTransientServices(IServiceCollection services)
                    {
                    }

                    /// <summary>
                    /// Adds additional services to the container.
                    /// </summary>
                    /// <param name="services">The service collection.</param>
                    static partial void AddAdditionalServices(IServiceCollection services);
                }
            }

            """;
        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Fact]
    public async Task WithPartialClassAndConfiguration_GeneratesExtensionClass()
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                [AutoInjectExtensions(MethodName = "AddCustomServices", IncludeConfiguration = true)]
                public static partial class MyServiceExtensions { }
            }
            """;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;

            namespace Test
            {
                /// <summary>
                /// Auto-generated extension methods for registering services with AutoInject attributes.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                static partial class MyServiceExtensions
                {
                    /// <summary>
                    /// Adds services decorated with AutoInject attributes from the assembly 'TestProject' to the IServiceCollection.
                    /// <para>
                    /// Implements the 'AddAdditionalServices' partial method to further customize service registrations.
                    /// </para>
                    /// </summary>
                    /// <param name="services">The IServiceCollection to add services to.</param>
                    /// <param name="configuration">The configuration.</param>
                    /// <returns>The IServiceCollection for chaining.</returns>
                    public static IServiceCollection AddCustomServices(this IServiceCollection services, global::Microsoft.Extensions.Configuration.IConfiguration configuration)
                    {
                        if (services == null) throw new global::System.ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);
                        AddAdditionalServices(services, configuration);

                        return services;
                    }

                    private static void AddSingletonServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddScopedServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddTransientServices(IServiceCollection services)
                    {
                    }

                    /// <summary>
                    /// Adds additional services to the container.
                    /// </summary>
                    /// <param name="services">The service collection.</param>
                    /// <param name="configuration">The configuration.</param>
                    static partial void AddAdditionalServices(IServiceCollection services, global::Microsoft.Extensions.Configuration.IConfiguration configuration);
                }
            }

            """;
        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task SingleService_NoServiceType_GeneratesRegistration(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                [{{lifetime}}Service]
                public class MyService
                {
                }
            }
            """;

        var expectedSingletonServices = lifetime == "Singleton"
            ? "services.TryAddSingleton<global::Test.MyService>();"
            : string.Empty;
        var expectedScopedServices = lifetime == "Scoped"
            ? "services.TryAddScoped<global::Test.MyService>();"
            : string.Empty;
        var expectedTransientServices = lifetime == "Transient"
            ? "services.TryAddTransient<global::Test.MyService>();"
            : string.Empty;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices,
            expectedScopedServices,
            expectedTransientServices
        );
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task SingleService_WithServiceType_GeneratesRegistration(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [{{lifetime}}Service(typeof(IFoo))]
                public class MyService : IFoo
                {
                }
            }
            """;

        var expectedSingletonServices = lifetime == "Singleton"
            ? "services.TryAddSingleton<global::Test.IFoo, global::Test.MyService>();"
            : string.Empty;
        var expectedScopedServices = lifetime == "Scoped"
            ? "services.TryAddScoped<global::Test.IFoo, global::Test.MyService>();"
            : string.Empty;
        var expectedTransientServices = lifetime == "Transient"
            ? "services.TryAddTransient<global::Test.IFoo, global::Test.MyService>();"
            : string.Empty;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices,
            expectedScopedServices,
            expectedTransientServices
        );
    }

    [Fact]
    public async Task UnifiedAttribute_GeneratesRegistration()
    {
        const string source = """
            using Ling.AutoInject;
            using Microsoft.Extensions.DependencyInjection;

            namespace Test;

            public interface IFoo { }

            [AutoInject(ServiceLifetime.Scoped, typeof(IFoo))]
            public sealed class MyService : IFoo;
            """;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices: string.Empty,
            expectedScopedServices: "services.TryAddScoped<global::Test.IFoo, global::Test.MyService>();",
            expectedTransientServices: string.Empty);
    }

    [Fact]
    public async Task RegisterImplementedInterfaces_GeneratesAllInterfaceRegistrations()
    {
        const string source = """
            using Ling.AutoInject;
            using Microsoft.Extensions.DependencyInjection;

            namespace Test;

            public interface IFoo { }
            public interface IBar { }

            [AutoInject(ServiceLifetime.Singleton, RegisterImplementedInterfaces = true)]
            public sealed class MyService : IFoo, IBar;
            """;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices: """
                services.TryAddSingleton<global::Test.IFoo, global::Test.MyService>();
                services.TryAddSingleton<global::Test.IBar, global::Test.MyService>();
                """,
            expectedScopedServices: string.Empty,
            expectedTransientServices: string.Empty);
    }

    [Theory]
    [InlineData("Add", "services.AddSingleton<global::Test.IFoo, global::Test.MyService>();")]
    [InlineData("TryAdd", "services.TryAddSingleton<global::Test.IFoo, global::Test.MyService>();")]
    [InlineData("Replace", "services.Replace(ServiceDescriptor.Singleton<global::Test.IFoo, global::Test.MyService>());")]
    [InlineData("TryAddEnumerable", "services.TryAddEnumerable(ServiceDescriptor.Singleton<global::Test.IFoo, global::Test.MyService>());")]
    public async Task RegistrationStrategy_GeneratesExpectedRegistration(string strategy, string expectedRegistration)
    {
        var source = $$"""
            using Ling.AutoInject;
            using Microsoft.Extensions.DependencyInjection;

            namespace Test;

            public interface IFoo { }

            [AutoInject(ServiceLifetime.Singleton, typeof(IFoo), Strategy = ServiceRegistrationStrategy.{{strategy}})]
            public sealed class MyService : IFoo;
            """;

        await VerifyGeneratedCodeAsync(source, expectedRegistration, string.Empty, string.Empty);
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task SelfAndTyped_BothSpecified_GeneratesBothRegistrations(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [{{lifetime}}Service]
                [{{lifetime}}Service(typeof(IFoo))]
                public class MyService : IFoo
                {
                }
            }
            """;

        var expectedSingletonServices = lifetime == "Singleton"
            ? """
              services.TryAddSingleton<global::Test.MyService>();
              services.TryAddSingleton<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());
              """
            : string.Empty;
        var expectedScopedServices = lifetime == "Scoped"
            ? """
              services.TryAddScoped<global::Test.MyService>();
              services.TryAddScoped<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());
              """
            : string.Empty;
        var expectedTransientServices = lifetime == "Transient"
            ? """
              services.TryAddTransient<global::Test.MyService>();
              services.TryAddTransient<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());
              """
            : string.Empty;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices,
            expectedScopedServices,
            expectedTransientServices
        );
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task MultipleAttributes_GeneratesImplementationRegistrations(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }
                public interface IBar { }

                [{{lifetime}}Service(typeof(IFoo))]
                [{{lifetime}}Service(typeof(IBar))]
                public class MyService : IFoo, IBar
                {
                }
            }
            """;

        var expectedSingletonServices = lifetime == "Singleton"
            ? """
              services.TryAddSingleton<global::Test.IFoo, global::Test.MyService>();
              services.TryAddSingleton<global::Test.IBar, global::Test.MyService>();
              """
            : string.Empty;
        var expectedScopedServices = lifetime == "Scoped"
            ? """
              services.TryAddScoped<global::Test.IFoo, global::Test.MyService>();
              services.TryAddScoped<global::Test.IBar, global::Test.MyService>();
              """
            : string.Empty;
        var expectedTransientServices = lifetime == "Transient"
            ? """
              services.TryAddTransient<global::Test.IFoo, global::Test.MyService>();
              services.TryAddTransient<global::Test.IBar, global::Test.MyService>();
              """
            : string.Empty;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices,
            expectedScopedServices,
            expectedTransientServices
        );
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task NamedServiceType_GeneratesTypedRegistration(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [{{lifetime}}Service(serviceType: typeof(IFoo))]
                public class MyService : IFoo
                {
                }
            }
            """;

        var expectedSingletonServices = lifetime == "Singleton"
            ? "services.TryAddSingleton<global::Test.IFoo, global::Test.MyService>();"
            : string.Empty;
        var expectedScopedServices = lifetime == "Scoped"
            ? "services.TryAddScoped<global::Test.IFoo, global::Test.MyService>();"
            : string.Empty;
        var expectedTransientServices = lifetime == "Transient"
            ? "services.TryAddTransient<global::Test.IFoo, global::Test.MyService>();"
            : string.Empty;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices,
            expectedScopedServices,
            expectedTransientServices
        );
    }

    #region Keyed Services

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task KeyedSingleService_NoServiceType_GeneratesRegistration(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                [{{lifetime}}Service(ServiceKey = "k1")]
                public class MyService
                {
                }
            }
            """;

        var expectedSingletonServices = lifetime == "Singleton"
#if NET8_0_OR_GREATER
            ? """global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedSingleton<global::Test.MyService, global::Test.MyService>("k1"), 1);"""
#else
            ? "services.TryAddSingleton<global::Test.MyService>();"
#endif
            : string.Empty;
        var expectedScopedServices = lifetime == "Scoped"
#if NET8_0_OR_GREATER
            ? """global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedScoped<global::Test.MyService, global::Test.MyService>("k1"), 1);"""
#else
            ? "services.TryAddScoped<global::Test.MyService>();"
#endif
            : string.Empty;
        var expectedTransientServices = lifetime == "Transient"
#if NET8_0_OR_GREATER
            ? """global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedTransient<global::Test.MyService, global::Test.MyService>("k1"), 1);"""
#else
            ? "services.TryAddTransient<global::Test.MyService>();"
#endif
            : string.Empty;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices,
            expectedScopedServices,
            expectedTransientServices
        );
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task KeyedSingleService_WithServiceType_GeneratesRegistration(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [{{lifetime}}Service(typeof(IFoo), ServiceKey = 1)]
                public class MyService : IFoo
                {
                }
            }
            """;

        var expectedSingletonServices = lifetime == "Singleton"
#if NET8_0_OR_GREATER
            ? "global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedSingleton<global::Test.IFoo, global::Test.MyService>(1), 1);"
#else
            ? "services.TryAddSingleton<global::Test.IFoo, global::Test.MyService>();"
#endif
            : string.Empty;
        var expectedScopedServices = lifetime == "Scoped"
#if NET8_0_OR_GREATER
            ? "global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedScoped<global::Test.IFoo, global::Test.MyService>(1), 1);"
#else
            ? "services.TryAddScoped<global::Test.IFoo, global::Test.MyService>();"
#endif
            : string.Empty;
        var expectedTransientServices = lifetime == "Transient"
#if NET8_0_OR_GREATER
            ? "global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedTransient<global::Test.IFoo, global::Test.MyService>(1), 1);"
#else
            ? "services.TryAddTransient<global::Test.IFoo, global::Test.MyService>();"
#endif
            : string.Empty;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices,
            expectedScopedServices,
            expectedTransientServices
        );
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task KeyedSelfAndTyped_BothSpecified_GeneratesRegistrations(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [{{lifetime}}Service(ServiceKey = MyService.Key)]
                [{{lifetime}}Service(typeof(IFoo), ServiceKey = MyService.Key)]
                public class MyService : IFoo
                {
                    public const string Key = "my-key";
                }
            }
            """;

        var expectedSingletonServices = lifetime == "Singleton"
#if NET8_0_OR_GREATER
            ? """
              global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedSingleton<global::Test.MyService, global::Test.MyService>("my-key"), 1);
              global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedSingleton<global::Test.IFoo>("my-key", (sp, key) => (global::Test.IFoo)sp.GetRequiredKeyedService<global::Test.MyService>(key)), 1);
              """
#else
            ? """
              services.TryAddSingleton<global::Test.MyService>();
              services.TryAddSingleton<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());
              """
#endif
            : string.Empty;
        var expectedScopedServices = lifetime == "Scoped"
#if NET8_0_OR_GREATER
            ? """
              global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedScoped<global::Test.MyService, global::Test.MyService>("my-key"), 1);
              global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedScoped<global::Test.IFoo>("my-key", (sp, key) => (global::Test.IFoo)sp.GetRequiredKeyedService<global::Test.MyService>(key)), 1);
              """
#else
            ? """
              services.TryAddScoped<global::Test.MyService>();
              services.TryAddScoped<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());
              """
#endif
            : string.Empty;
        var expectedTransientServices = lifetime == "Transient"
#if NET8_0_OR_GREATER
            ? """
              global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedTransient<global::Test.MyService, global::Test.MyService>("my-key"), 1);
              global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedTransient<global::Test.IFoo>("my-key", (sp, key) => (global::Test.IFoo)sp.GetRequiredKeyedService<global::Test.MyService>(key)), 1);
              """
#else
            ? """
              services.TryAddTransient<global::Test.MyService>();
              services.TryAddTransient<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());
              """
#endif
            : string.Empty;

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices,
            expectedScopedServices,
            expectedTransientServices
        );
    }

    [Fact]
    public async Task KeyedTypedServices_AllLifetimes_GeneratesRegistrations()
    {
        const string source = """
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }
                public interface IBar { }
                public interface IBaz { }

                [SingletonService(ServiceKey = 1)]
                [SingletonService(typeof(IFoo), ServiceKey = 1)]
                public class FooService : IFoo { }

                [ScopedService(ServiceKey = "k1")]
                [ScopedService(typeof(IBar), ServiceKey = "k2")]
                public class BarService : IBar { }

                [TransientService(typeof(IBaz), ServiceKey = 1.1)]
                [TransientService(typeof(IBaz), ServiceKey = 1.2)]
                public class BazService : IBaz { }
            }
            """;

        var expectedSingletonServices =
#if NET8_0_OR_GREATER
            """
            global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedSingleton<global::Test.FooService, global::Test.FooService>(1), 1);
            global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedSingleton<global::Test.IFoo>(1, (sp, key) => (global::Test.IFoo)sp.GetRequiredKeyedService<global::Test.FooService>(key)), 1);
            """;
#else
            """
            services.TryAddSingleton<global::Test.FooService>();
            services.TryAddSingleton<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.FooService>());
            """;
#endif
        var expectedScopedServices =
#if NET8_0_OR_GREATER
            """
            global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedScoped<global::Test.BarService, global::Test.BarService>("k1"), 1);
            global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedScoped<global::Test.IBar, global::Test.BarService>("k2"), 1);
            """;
#else
            """
            services.TryAddScoped<global::Test.BarService>();
            services.TryAddScoped<global::Test.IBar>(sp => (global::Test.IBar)sp.GetRequiredService<global::Test.BarService>());
            """;
#endif
        var expectedTransientServices =
#if NET8_0_OR_GREATER
            """
            global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedTransient<global::Test.IBaz, global::Test.BazService>(1.1), 1);
            global::Ling.AutoInject.AutoInjectKeyedRegistration.Add(services, ServiceDescriptor.KeyedTransient<global::Test.IBaz, global::Test.BazService>(1.2), 1);
            """;
#else
            """
            services.TryAddTransient<global::Test.IBaz, global::Test.BazService>();
            """;
#endif

        await VerifyGeneratedCodeAsync(
            source,
            expectedSingletonServices,
            expectedScopedServices,
            expectedTransientServices
        );
    }

    #endregion Keyed Services
}
