using VerifyCS = Ling.AutoInject.SourceGenerators.Tests.Verifiers.CSharpSourceGeneratorVerifier<
    Ling.AutoInject.SourceGenerators.AutoInjectGenerator>;

namespace Ling.AutoInject.SourceGenerators.Tests;

public class AutoInjectGeneratorTests
{
    private static async Task VerifyGeneratedCodeAsync(string source, string expectedGeneratedCode)
    {
        await VerifyCS.VerifySourceGeneratorAsync(
            source,
            ("AutoInjectConfigAttribute.g.cs", SourceCodes.AutoInjectConfigAttribute),
            ("SingletonServiceAttribute.g.cs", SourceCodes.SingletonServiceAttribute),
            ("ScopedServiceAttribute.g.cs", SourceCodes.ScopedServiceAttribute),
            ("TransientServiceAttribute.g.cs", SourceCodes.TransientServiceAttribute),
            ("AutoInject_TestProject.g.cs", expectedGeneratedCode));
    }

    [Fact]
    public async Task AutoInjectGenerator_WithCustomMethod_GeneratesExtensionClass()
    {
        const string source = """
            [assembly: Ling.AutoInject.AutoInjectConfig(MethodName = "AddCustomServices", ClassName = "ServiceExtensions", Namespace = "MyNamespace")]
            """;
        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace MyNamespace
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class ServiceExtensions
                {
                    public static IServiceCollection AddCustomServices(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }

                    private static void AddSingletonServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddScopedServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddTransientServices(IServiceCollection services)
                    {
                    }
                }
            }

            """;
        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task AutoInjectGenerator_SingleService_NoServiceType_GeneratesRegistration(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                [{{lifetime}}Service]
                public class MyService
                {
                }
            }
            """;

        var singletonBody = lifetime == "Singleton"
            ? Environment.NewLine + "            services.TryAddSingleton<global::Test.MyService>();"
            : string.Empty;
        var scopedBody = lifetime == "Scoped"
            ? Environment.NewLine + "            services.TryAddScoped<global::Test.MyService>();"
            : string.Empty;
        var transientBody = lifetime == "Transient"
            ? Environment.NewLine + "            services.TryAddTransient<global::Test.MyService>();"
            : string.Empty;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace TestProject.Extensions
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class AutoInject_TestProject_Generated
                {
                    public static IServiceCollection AddAutoInjectFor_TestProject(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }

                    private static void AddSingletonServices(IServiceCollection services)
                    {{{singletonBody}}
                    }

                    private static void AddScopedServices(IServiceCollection services)
                    {{{scopedBody}}
                    }
 
                    private static void AddTransientServices(IServiceCollection services)
                    {{{transientBody}}
                    }
                }
            }

            """;

        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task AutoInjectGenerator_SingleService_WithServiceType_GeneratesRegistration(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [{{lifetime}}Service(typeof(IFoo))]
                public class MyService : IFoo
                {
                }
            }
            """;

        var singletonBody = lifetime == "Singleton"
            ? Environment.NewLine + "            services.TryAddSingleton<global::Test.IFoo, global::Test.MyService>();"
            : string.Empty;
        var scopedBody = lifetime == "Scoped"
            ? Environment.NewLine + "            services.TryAddScoped<global::Test.IFoo, global::Test.MyService>();"
            : string.Empty;
        var transientBody = lifetime == "Transient"
            ? Environment.NewLine + "            services.TryAddTransient<global::Test.IFoo, global::Test.MyService>();"
            : string.Empty;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace TestProject.Extensions
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class AutoInject_TestProject_Generated
                {
                    public static IServiceCollection AddAutoInjectFor_TestProject(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }
            
                    private static void AddSingletonServices(IServiceCollection services)
                    {{{singletonBody}}
                    }
            
                    private static void AddScopedServices(IServiceCollection services)
                    {{{scopedBody}}
                    }
            
                    private static void AddTransientServices(IServiceCollection services)
                    {{{transientBody}}
                    }
                }
            }

            """;
        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task AutoInjectGenerator_SelfAndTyped_BothSpecified_GeneratesBothRegistrations(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [{{lifetime}}Service]
                [{{lifetime}}Service(typeof(IFoo))]
                public class MyService : IFoo
                {
                }
            }
            """;

        var singletonBody = lifetime == "Singleton"
            ? Environment.NewLine + "            services.TryAddSingleton<global::Test.MyService>();"
            + Environment.NewLine + "            services.TryAddSingleton<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());"
            : string.Empty;
        var scopedBody = lifetime == "Scoped"
            ? Environment.NewLine + "            services.TryAddScoped<global::Test.MyService>();"
            + Environment.NewLine + "            services.TryAddScoped<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());"
            : string.Empty;
        var transientBody = lifetime == "Transient"
            ? Environment.NewLine + "            services.TryAddTransient<global::Test.MyService>();"
            + Environment.NewLine + "            services.TryAddTransient<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());"
            : string.Empty;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace TestProject.Extensions
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class AutoInject_TestProject_Generated
                {
                    public static IServiceCollection AddAutoInjectFor_TestProject(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }
            
                    private static void AddSingletonServices(IServiceCollection services)
                    {{{singletonBody}}
                    }
            
                    private static void AddScopedServices(IServiceCollection services)
                    {{{scopedBody}}
                    }
            
                    private static void AddTransientServices(IServiceCollection services)
                    {{{transientBody}}
                    }
                }
            }

            """;

        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Fact]
    public async Task AutoInjectGenerator_MultipleAttributes_GeneratesImplementationRegistrations()
    {
        const string source = """
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }
                public interface IBar { }

                [ScopedService(typeof(IFoo))]
                [ScopedService(typeof(IBar))]
                public class MyService : IFoo, IBar
                {
                }
            }
            """;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace TestProject.Extensions
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class AutoInject_TestProject_Generated
                {
                    public static IServiceCollection AddAutoInjectFor_TestProject(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }

                    private static void AddSingletonServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddScopedServices(IServiceCollection services)
                    {
                        services.TryAddScoped<global::Test.IFoo, global::Test.MyService>();
                        services.TryAddScoped<global::Test.IBar>(sp => (global::Test.IBar)sp.GetRequiredService<global::Test.IFoo>());
                    }
 
                    private static void AddTransientServices(IServiceCollection services)
                    {
                    }
                }
            }

            """;

        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Fact]
    public async Task AutoInjectGenerator_NamedServiceType_GeneratesTypedRegistration()
    {
        const string source = """
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [ScopedService(serviceType: typeof(IFoo))]
                public class MyService : IFoo
                {
                }
            }
            """;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace TestProject.Extensions
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class AutoInject_TestProject_Generated
                {
                    public static IServiceCollection AddAutoInjectFor_TestProject(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }

                    private static void AddSingletonServices(IServiceCollection services)
                    {
                    }
 
                    private static void AddScopedServices(IServiceCollection services)
                    {
                        services.TryAddScoped<global::Test.IFoo, global::Test.MyService>();
                    }
 
                    private static void AddTransientServices(IServiceCollection services)
                    {
                    }
                }
            }

            """;
        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    #region Keyed Services

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task AutoInjectGenerator_KeyedSingleService_NoServiceType_GeneratesRegistration(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                [{{lifetime}}Service(ServiceKey = "k1")]
                public class MyService
                {
                }
            }
            """;

        var singletonBody = lifetime == "Singleton"
#if NET8_0_OR_GREATER
            ? Environment.NewLine + """            services.TryAddKeyedSingleton<global::Test.MyService>("k1");"""
#else
            ? Environment.NewLine + """            services.TryAddSingleton<global::Test.MyService>();"""
#endif
            : string.Empty;
        var scopedBody = lifetime == "Scoped"
#if NET8_0_OR_GREATER
            ? Environment.NewLine + """            services.TryAddKeyedScoped<global::Test.MyService>("k1");"""
#else
            ? Environment.NewLine + """            services.TryAddScoped<global::Test.MyService>();"""
#endif
            : string.Empty;
        var transientBody = lifetime == "Transient"
#if NET8_0_OR_GREATER
            ? Environment.NewLine + """            services.TryAddKeyedTransient<global::Test.MyService>("k1");"""
#else
            ? Environment.NewLine + """            services.TryAddTransient<global::Test.MyService>();"""
#endif
            : string.Empty;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace TestProject.Extensions
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class AutoInject_TestProject_Generated
                {
                    public static IServiceCollection AddAutoInjectFor_TestProject(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }

                    private static void AddSingletonServices(IServiceCollection services)
                    {{{singletonBody}}
                    }

                    private static void AddScopedServices(IServiceCollection services)
                    {{{scopedBody}}
                    }
 
                    private static void AddTransientServices(IServiceCollection services)
                    {{{transientBody}}
                    }
                }
            }

            """;

        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task AutoInjectGenerator_KeyedSingleService_WithServiceType_GeneratesRegistration(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [{{lifetime}}Service(typeof(IFoo), ServiceKey = 1)]
                public class MyService : IFoo
                {
                }
            }
            """;

        var singletonBody = lifetime == "Singleton"
#if NET8_0_OR_GREATER
            ? Environment.NewLine + "            services.TryAddKeyedSingleton<global::Test.IFoo, global::Test.MyService>(1);"
#else
            ? Environment.NewLine + "            services.TryAddSingleton<global::Test.IFoo, global::Test.MyService>();"
#endif
            : string.Empty;
        var scopedBody = lifetime == "Scoped"
#if NET8_0_OR_GREATER
            ? Environment.NewLine + "            services.TryAddKeyedScoped<global::Test.IFoo, global::Test.MyService>(1);"
#else
            ? Environment.NewLine + "            services.TryAddScoped<global::Test.IFoo, global::Test.MyService>();"
#endif
            : string.Empty;
        var transientBody = lifetime == "Transient"
#if NET8_0_OR_GREATER
            ? Environment.NewLine + "            services.TryAddKeyedTransient<global::Test.IFoo, global::Test.MyService>(1);"
#else
            ? Environment.NewLine + "            services.TryAddTransient<global::Test.IFoo, global::Test.MyService>();"
#endif
            : string.Empty;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace TestProject.Extensions
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class AutoInject_TestProject_Generated
                {
                    public static IServiceCollection AddAutoInjectFor_TestProject(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }
            
                    private static void AddSingletonServices(IServiceCollection services)
                    {{{singletonBody}}
                    }
            
                    private static void AddScopedServices(IServiceCollection services)
                    {{{scopedBody}}
                    }
            
                    private static void AddTransientServices(IServiceCollection services)
                    {{{transientBody}}
                    }
                }
            }

            """;
        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Theory]
    [InlineData("Singleton")]
    [InlineData("Scoped")]
    [InlineData("Transient")]
    public async Task AutoInjectGenerator_Keyed_SelfAndTyped_BothSpecified_GeneratesRegistrations(string lifetime)
    {
        var source = $$"""
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }

                [{{lifetime}}Service(ServiceKey = MyService.Key)]
                [{{lifetime}}Service(typeof(IFoo), ServiceKey = MyService.Key)]
                public class MyService : IFoo
                {
                    public const string Key = "my-key";
                }
            }
            """;

        var singletonBody = lifetime == "Singleton"
#if NET8_0_OR_GREATER
            ? Environment.NewLine + """            services.TryAddKeyedSingleton<global::Test.MyService>("my-key");"""
            + Environment.NewLine + """            services.TryAddKeyedSingleton<global::Test.IFoo>("my-key", (sp, key) => (global::Test.IFoo)sp.GetRequiredKeyedService<global::Test.MyService>(key));"""
#else
            ? Environment.NewLine + """            services.TryAddSingleton<global::Test.MyService>();"""
            + Environment.NewLine + """            services.TryAddSingleton<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());"""
#endif
            : string.Empty;
        var scopedBody = lifetime == "Scoped"
#if NET8_0_OR_GREATER
            ? Environment.NewLine + """            services.TryAddKeyedScoped<global::Test.MyService>("my-key");"""
            + Environment.NewLine + """            services.TryAddKeyedScoped<global::Test.IFoo>("my-key", (sp, key) => (global::Test.IFoo)sp.GetRequiredKeyedService<global::Test.MyService>(key));"""
#else
            ? Environment.NewLine + """            services.TryAddScoped<global::Test.MyService>();"""
            + Environment.NewLine + """            services.TryAddScoped<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());"""
#endif
            : string.Empty;
        var transientBody = lifetime == "Transient"
#if NET8_0_OR_GREATER
            ? Environment.NewLine + """            services.TryAddKeyedTransient<global::Test.MyService>("my-key");"""
            + Environment.NewLine + """            services.TryAddKeyedTransient<global::Test.IFoo>("my-key", (sp, key) => (global::Test.IFoo)sp.GetRequiredKeyedService<global::Test.MyService>(key));"""
#else
            ? Environment.NewLine + """            services.TryAddTransient<global::Test.MyService>();"""
            + Environment.NewLine + """            services.TryAddTransient<global::Test.IFoo>(sp => (global::Test.IFoo)sp.GetRequiredService<global::Test.MyService>());"""
#endif
            : string.Empty;

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace TestProject.Extensions
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class AutoInject_TestProject_Generated
                {
                    public static IServiceCollection AddAutoInjectFor_TestProject(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }
            
                    private static void AddSingletonServices(IServiceCollection services)
                    {{{singletonBody}}
                    }
            
                    private static void AddScopedServices(IServiceCollection services)
                    {{{scopedBody}}
                    }
            
                    private static void AddTransientServices(IServiceCollection services)
                    {{{transientBody}}
                    }
                }
            }

            """;

        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    [Fact]
    public async Task AutoInjectGenerator_KeyedTypedServices_AllLifetimes_GeneratesRegistrations()
    {
        const string source = """
            using Ling.AutoInject;

            namespace Test
            {
                public interface IFoo { }
                public interface IBar { }
                public interface IBaz { }

                [SingletonService(typeof(IFoo), ServiceKey = 1)]
                public class FooService : IFoo { }

                [ScopedService(typeof(IBar), ServiceKey = "s2")]
                public class BarService : IBar { }

                [TransientService(typeof(IBaz), ServiceKey = 99)]
                public class BazService : IBaz { }
            }
            """;

        var singletonBody =
#if NET8_0_OR_GREATER
            Environment.NewLine + """            services.TryAddKeyedSingleton<global::Test.IFoo, global::Test.FooService>(1);""";
#else
            Environment.NewLine + """            services.TryAddSingleton<global::Test.IFoo, global::Test.FooService>();""";
#endif
        var scopedBody =
#if NET8_0_OR_GREATER
            Environment.NewLine + """            services.TryAddKeyedScoped<global::Test.IBar, global::Test.BarService>("s2");""";
#else
            Environment.NewLine + """            services.TryAddScoped<global::Test.IBar, global::Test.BarService>();""";
#endif
        var transientBody =
#if NET8_0_OR_GREATER
            Environment.NewLine + """            services.TryAddKeyedTransient<global::Test.IBaz, global::Test.BazService>(99);""";
#else
            Environment.NewLine + """            services.TryAddTransient<global::Test.IBaz, global::Test.BazService>();""";
#endif

        var generatedCode = $$"""
            // <auto-generated />
            
            #pragma warning disable
            #nullable enable annotations

            using Microsoft.Extensions.DependencyInjection;

            namespace TestProject.Extensions
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                public static class AutoInject_TestProject_Generated
                {
                    public static IServiceCollection AddAutoInjectFor_TestProject(this IServiceCollection services)
                    {
                        if (services == null) throw new ArgumentNullException(nameof(services));

                        AddSingletonServices(services);
                        AddScopedServices(services);
                        AddTransientServices(services);

                        return services;
                    }
            
                    private static void AddSingletonServices(IServiceCollection services)
                    {{{singletonBody}}
                    }
            
                    private static void AddScopedServices(IServiceCollection services)
                    {{{scopedBody}}
                    }
            
                    private static void AddTransientServices(IServiceCollection services)
                    {{{transientBody}}
                    }
                }
            }

            """;
        await VerifyGeneratedCodeAsync(source, generatedCode);
    }

    #endregion Keyed Services
}
