//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ling.AutoInject.SourceGenerators.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ling.AutoInject.SourceGenerators.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The configured AutoInject extension method name &apos;{0}&apos; is already used by an existing extension method taking &apos;this IServiceCollection&apos; as the first parameter. Choose a different MethodName in AutoInjectConfig to avoid conflicts. 的本地化字符串。
        /// </summary>
        internal static string ConflictingExtension_Message {
            get {
                return ResourceManager.GetString("ConflictingExtension_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conflicting extension method for IServiceCollection 的本地化字符串。
        /// </summary>
        internal static string ConflictingExtension_Title {
            get {
                return ResourceManager.GetString("ConflictingExtension_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A class cannot be registered with multiple conflicting service lifetimes. 的本地化字符串。
        /// </summary>
        internal static string ConflictingLifetime_Message {
            get {
                return ResourceManager.GetString("ConflictingLifetime_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conflicting service lifetimes 的本地化字符串。
        /// </summary>
        internal static string ConflictingLifetime_Title {
            get {
                return ResourceManager.GetString("ConflictingLifetime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate service registration attribute detected for the same service type and lifetime. 的本地化字符串。
        /// </summary>
        internal static string DuplicateAttribute_Message {
            get {
                return ResourceManager.GetString("DuplicateAttribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate service registration attribute 的本地化字符串。
        /// </summary>
        internal static string DuplicateAttribute_Title {
            get {
                return ResourceManager.GetString("DuplicateAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a valid {1}. A valid C# identifier is required. 的本地化字符串。
        /// </summary>
        internal static string InvalidNaming_Message {
            get {
                return ResourceManager.GetString("InvalidNaming_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid AutoInject configuration 的本地化字符串。
        /// </summary>
        internal static string InvalidNaming_Title {
            get {
                return ResourceManager.GetString("InvalidNaming_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple &apos;AutoInjectExtensions&apos; declarations were found in the assembly; only one is allowed. 的本地化字符串。
        /// </summary>
        internal static string MultipleExtensionsUsed_Message {
            get {
                return ResourceManager.GetString("MultipleExtensionsUsed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple AutoInject extension declarations 的本地化字符串。
        /// </summary>
        internal static string MultipleExtensionsUsed_Title {
            get {
                return ResourceManager.GetString("MultipleExtensionsUsed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyed service registrations require &apos;Microsoft.Extensions.DependencyInjection.Abstractions&apos; version 8.0.0 or later. 的本地化字符串。
        /// </summary>
        internal static string NotSupportedKeyedService_Message {
            get {
                return ResourceManager.GetString("NotSupportedKeyedService_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyed service registration not supported 的本地化字符串。
        /// </summary>
        internal static string NotSupportedKeyedService_Title {
            get {
                return ResourceManager.GetString("NotSupportedKeyedService_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace service registrations require &apos;Microsoft.Extensions.DependencyInjection.Abstractions&apos; version 8.0.0 or later. 的本地化字符串。
        /// </summary>
        internal static string NotSupportedReplaceService_Message {
            get {
                return ResourceManager.GetString("NotSupportedReplaceService_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace service registration not supported 的本地化字符串。
        /// </summary>
        internal static string NotSupportedReplaceService_Title {
            get {
                return ResourceManager.GetString("NotSupportedReplaceService_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A service type must be specified when using Replace service registration. 的本地化字符串。
        /// </summary>
        internal static string RequiredServiceTypeForReplace_Message {
            get {
                return ResourceManager.GetString("RequiredServiceTypeForReplace_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required service type for Replace registration 的本地化字符串。
        /// </summary>
        internal static string RequiredServiceTypeForReplace_Title {
            get {
                return ResourceManager.GetString("RequiredServiceTypeForReplace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target class &apos;{0}&apos; must be declared as &apos;static partial&apos; to host generated extension methods. 的本地化字符串。
        /// </summary>
        internal static string RequiredStaticPartialClass_Message {
            get {
                return ResourceManager.GetString("RequiredStaticPartialClass_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generated extension host must be static partial class 的本地化字符串。
        /// </summary>
        internal static string RequiredStaticPartialClass_Title {
            get {
                return ResourceManager.GetString("RequiredStaticPartialClass_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The service type &apos;{0}&apos; is either not an interface or is not implemented by &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ServiceTypeMismatch_Message {
            get {
                return ResourceManager.GetString("ServiceTypeMismatch_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service type mismatch 的本地化字符串。
        /// </summary>
        internal static string ServiceTypeMismatch_Title {
            get {
                return ResourceManager.GetString("ServiceTypeMismatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The assembly-level AutoInjectConfig attribute is unnecessary when an AutoInjectExtensions attribute is present. 的本地化字符串。
        /// </summary>
        internal static string UnnecessaryConfigUsage_Message {
            get {
                return ResourceManager.GetString("UnnecessaryConfigUsage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unnecessary AutoInject configuration 的本地化字符串。
        /// </summary>
        internal static string UnnecessaryConfigUsage_Title {
            get {
                return ResourceManager.GetString("UnnecessaryConfigUsage_Title", resourceCulture);
            }
        }
    }
}
