name: Setup Environment
description: Sets up the environment for the workflow

env:
  # Necessary for installing OpenSSL 1.1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

runs:
  using: "composite"
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
          7.0.x
          8.0.x
          9.0.x
          10.0.x

    - name: Install OpenSSL
      shell: bash
      run: |
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb