name: Setup Environment
description: Sets up the environment for the workflow

runs:
  using: "composite"
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
          7.0.x
          8.0.x
          9.0.x
          10.0.x

    - name: Install OpenSSL 1.1
      run: sudo apt-get install libssl1.0.2