namespace Ling.AutoInject.SourceGenerators;

/// <summary>
/// Holds the source code strings for the attributes used in the source generator.
/// </summary>
internal static class SourceCodes
{
    public static string AutoInjectConfigAttribute { get; } = $$"""
        // <auto-generated />
        
        #pragma warning disable
        #nullable enable
        
        namespace Ling.AutoInject
        {
            /// <summary>
            /// Marks a class as the configuration for automatic dependency injection registration.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class AutoInjectConfigAttribute : global::System.Attribute
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="AutoInjectConfigAttribute"/> class.
                /// </summary>
                public AutoInjectConfigAttribute()
                {
                }

                /// <summary>
                /// Gets or sets the method name to configure services.
                /// </summary>
                public string? MethodName { get; set; }

                /// <summary>
                /// Gets or sets the class name containing the configuration method.
                /// </summary>
                public string? ClassName { get; set; }

                /// <summary>
                /// Gets or sets the namespace for the generated configuration class.
                /// </summary>
                public string? Namespace { get; set; }
            }
        }
        """;

    /// <summary>
    /// The source code for the SingletonServiceAttribute.
    /// </summary>
    public static string SingletonServiceAttribute { get; } = $$"""
        // <auto-generated />
        
        #pragma warning disable
        #nullable enable
        
        namespace Ling.AutoInject
        {
            /// <summary>
            /// Marks a class for automatic registration as a singleton service in the dependency injection container.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class SingletonServiceAttribute : global::System.Attribute
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="SingletonServiceAttribute"/> class.
                /// </summary>
                public SingletonServiceAttribute()
                {
                }
        
                /// <summary>
                /// Initializes a new instance of the <see cref="SingletonServiceAttribute"/> class with the specified service type.
                /// </summary>
                /// <param name="serviceType">The service type to register.</param>
                public SingletonServiceAttribute(global::System.Type serviceType)
                {
                    ServiceType = serviceType;
                }
        
                /// <summary>
                /// Gets the service type to register.
                /// </summary>
                public global::System.Type? ServiceType { get; }
        
                /// <summary>
                /// Gets or sets the service key for keyed service registration.
                /// </summary>
                public object? ServiceKey { get; set; }
            }
        }
        """;

    /// <summary>
    /// The source code for the ScopedServiceAttribute.
    /// </summary>
    public static string ScopedServiceAttribute { get; } = $$"""
        // <auto-generated />
        
        #pragma warning disable
        #nullable enable
        
        namespace Ling.AutoInject
        {
            /// <summary>
            /// Marks a class for automatic registration as a scoped service in the dependency injection container.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class ScopedServiceAttribute : global::System.Attribute
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="ScopedServiceAttribute"/> class.
                /// </summary>
                public ScopedServiceAttribute()
                {
                }
        
                /// <summary>
                /// Initializes a new instance of the <see cref="ScopedServiceAttribute"/> class with the specified service type.
                /// </summary>
                /// <param name="serviceType">The service type to register.</param>
                public ScopedServiceAttribute(global::System.Type serviceType)
                {
                    ServiceType = serviceType;
                }
        
                /// <summary>
                /// Gets the service type to register.
                /// </summary>
                public global::System.Type? ServiceType { get; }
        
                /// <summary>
                /// Gets or sets the service key for keyed service registration.
                /// </summary>
                public object? ServiceKey { get; set; }
            }
        }
        """;

    /// <summary>
    /// The source code for the TransientServiceAttribute.
    /// </summary>
    public static string TransientServiceAttribute { get; } = $$"""
        // <auto-generated />
        
        #pragma warning disable
        #nullable enable
        
        namespace Ling.AutoInject
        {
            /// <summary>
            /// Marks a class for automatic registration as a transient service in the dependency injection container.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class TransientServiceAttribute : global::System.Attribute
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="TransientServiceAttribute"/> class.
                /// </summary>
                public TransientServiceAttribute()
                {
                }
        
                /// <summary>
                /// Initializes a new instance of the <see cref="TransientServiceAttribute"/> class with the specified service type.
                /// </summary>
                /// <param name="serviceType">The service type to register.</param>
                public TransientServiceAttribute(global::System.Type serviceType)
                {
                    ServiceType = serviceType;
                }
        
                /// <summary>
                /// Gets the service type to register.
                /// </summary>
                public global::System.Type? ServiceType { get; }
        
                /// <summary>
                /// Gets or sets the service key for keyed service registration.
                /// </summary>
                public object? ServiceKey { get; set; }
            }
        }
        """;
}
