namespace Ling.AutoInject.SourceGenerators;

/// <summary>
/// Holds the source code strings for the attributes used in the source generator.
/// </summary>
internal static class SourceCodes
{
    public static string KeyedRegistration { get; } = """
        // <auto-generated />
        #nullable enable
        namespace Ling.AutoInject
        {
            // DI 8.0 initially compared boxed keys by reference. Use value equality on
            // every supported version, matching the container's service resolution.
            internal static class AutoInjectKeyedRegistration
            {
                internal static void Add(
                    global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                    global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor,
                    int strategy)
                {
                    if (strategy != 0)
                    {
                        for (var i = 0; i < services.Count; i++)
                        {
                            var existing = services[i];
                            if (existing.ServiceType != descriptor.ServiceType ||
                                !global::System.Object.Equals(existing.ServiceKey, descriptor.ServiceKey)) continue;
                            if (strategy == 2)
                            {
                                services.RemoveAt(i);
                                break;
                            }
                            if (strategy == 1 || GetImplementationType(existing) == descriptor.KeyedImplementationType) return;
                        }
                    }
                    services.Add(descriptor);
                }

                private static global::System.Type? GetImplementationType(
                    global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor)
                {
                    if (!descriptor.IsKeyedService) return null;
                    return descriptor.KeyedImplementationType
                        ?? descriptor.KeyedImplementationInstance?.GetType()
                        ?? descriptor.KeyedImplementationFactory?.GetType().GenericTypeArguments[2];
                }
            }
        }
        """;

    public static string AutoInjectAttribute { get; } = $$"""
        // <auto-generated />

        #pragma warning disable
        #nullable enable

        namespace Ling.AutoInject
        {
            /// <summary>
            /// Specifies the registration strategy used by AutoInject.
            /// </summary>
            internal enum ServiceRegistrationStrategy
            {
                /// <summary>Appends a registration on every call.</summary>
                Add = 0,
                /// <summary>Preserves an existing registration for the service type and key.</summary>
                TryAdd = 1,
                /// <summary>Replaces the first registration for the service type and key.</summary>
                Replace = 2,
                /// <summary>Adds each implementation once per service type and key.</summary>
                TryAddEnumerable = 3,
            }

            /// <summary>
            /// Marks a class for automatic dependency injection registration with a specified lifetime.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class AutoInjectAttribute : global::System.Attribute
            {
                public AutoInjectAttribute(global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime)
                {
                    Lifetime = lifetime;
                }

                public AutoInjectAttribute(global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime, global::System.Type serviceType)
                    : this(lifetime)
                {
                    ServiceType = serviceType;
                }

                /// <summary>Gets the registration lifetime.</summary>
                public global::Microsoft.Extensions.DependencyInjection.ServiceLifetime Lifetime { get; }

                /// <summary>Gets or sets the service interface; a named value overrides the constructor value.</summary>
                public global::System.Type? ServiceType { get; set; }

                /// <summary>Gets or sets the key; null means an unkeyed registration.</summary>
                public object? ServiceKey { get; set; }

                /// <summary>Gets or sets the registration strategy. Defaults to TryAdd.</summary>
                public ServiceRegistrationStrategy Strategy { get; set; } = ServiceRegistrationStrategy.TryAdd;

                /// <summary>Registers all implemented interfaces instead of the implementation itself.</summary>
                public bool RegisterImplementedInterfaces { get; set; }
            }
        }
        """;

    public static string AutoInjectConfigAttribute { get; } = $$"""
        // <auto-generated />
        
        #pragma warning disable
        #nullable enable
        
        namespace Ling.AutoInject
        {
            /// <summary>
            /// Marks a class as the configuration for automatic dependency injection registration.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class AutoInjectConfigAttribute : global::System.Attribute
            {
                /// <summary>
                /// Gets or sets the method name to configure services.
                /// </summary>
                public string? MethodName { get; set; }

                /// <summary>
                /// Gets or sets the class name containing the configuration method.
                /// </summary>
                public string? ClassName { get; set; }

                /// <summary>
                /// Gets or sets the namespace for the generated configuration class.
                /// </summary>
                public string? Namespace { get; set; }
            }
        }
        """;

    public static string AutoInjectExtensionsAttribute { get; } = $$"""
        // <auto-generated />
        
        #pragma warning disable
        #nullable enable
        
        namespace Ling.AutoInject
        {
            /// <summary>
            /// Marks a static partial class to generate extension methods for service registration.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class AutoInjectExtensionsAttribute : global::System.Attribute
            {
                /// <summary>
                /// Gets or sets the name of the method to generate.
                /// </summary>
                public string? MethodName { get; set; }

                /// <summary>
                /// Gets or sets a value indicating whether to include 'IConfiguration' in the generated method.
                /// </summary>
                public bool IncludeConfiguration { get; set; }
            }
        }
        """;

    /// <summary>
    /// The source code for the SingletonServiceAttribute.
    /// </summary>
    public static string SingletonServiceAttribute { get; } = $$"""
        // <auto-generated />
        
        #pragma warning disable
        #nullable enable
        
        namespace Ling.AutoInject
        {
            /// <summary>
            /// Marks a class for automatic registration as a singleton service in the dependency injection container.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class SingletonServiceAttribute : global::System.Attribute
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="SingletonServiceAttribute"/> class.
                /// </summary>
                public SingletonServiceAttribute()
                {
                }
        
                /// <summary>
                /// Initializes a new instance of the <see cref="SingletonServiceAttribute"/> class with the specified service type.
                /// </summary>
                /// <param name="serviceType">The service type to register.</param>
                public SingletonServiceAttribute(global::System.Type serviceType)
                {
                    ServiceType = serviceType;
                }
        
                /// <summary>
                /// Gets the service type to register.
                /// </summary>
                public global::System.Type? ServiceType { get; }
        
                /// <summary>
                /// Gets or sets the service key for keyed service registration.
                /// </summary>
                public object? ServiceKey { get; set; }

                /// <summary>
                /// Gets or sets a value indicating whether the generated registration should replace existing registrations for the service type.
                /// </summary>
                public bool Replace { get; set; }

                /// <summary>
                /// Gets or sets the strategy used to register the service.
                /// </summary>
                public ServiceRegistrationStrategy Strategy { get; set; } = ServiceRegistrationStrategy.TryAdd;

                /// <summary>
                /// Gets or sets a value indicating whether all implemented interfaces should be registered.
                /// </summary>
                public bool RegisterImplementedInterfaces { get; set; }
            }
        }
        """;

    /// <summary>
    /// The source code for the ScopedServiceAttribute.
    /// </summary>
    public static string ScopedServiceAttribute { get; } = $$"""
        // <auto-generated />
        
        #pragma warning disable
        #nullable enable
        
        namespace Ling.AutoInject
        {
            /// <summary>
            /// Marks a class for automatic registration as a scoped service in the dependency injection container.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class ScopedServiceAttribute : global::System.Attribute
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="ScopedServiceAttribute"/> class.
                /// </summary>
                public ScopedServiceAttribute()
                {
                }
        
                /// <summary>
                /// Initializes a new instance of the <see cref="ScopedServiceAttribute"/> class with the specified service type.
                /// </summary>
                /// <param name="serviceType">The service type to register.</param>
                public ScopedServiceAttribute(global::System.Type serviceType)
                {
                    ServiceType = serviceType;
                }
        
                /// <summary>
                /// Gets the service type to register.
                /// </summary>
                public global::System.Type? ServiceType { get; }
        
                /// <summary>
                /// Gets or sets the service key for keyed service registration.
                /// </summary>
                public object? ServiceKey { get; set; }

                /// <summary>
                /// Gets or sets a value indicating whether the generated registration should replace existing registrations for the service type.
                /// </summary>
                public bool Replace { get; set; }

                /// <summary>
                /// Gets or sets the strategy used to register the service.
                /// </summary>
                public ServiceRegistrationStrategy Strategy { get; set; } = ServiceRegistrationStrategy.TryAdd;

                /// <summary>
                /// Gets or sets a value indicating whether all implemented interfaces should be registered.
                /// </summary>
                public bool RegisterImplementedInterfaces { get; set; }
            }
        }
        """;

    /// <summary>
    /// The source code for the TransientServiceAttribute.
    /// </summary>
    public static string TransientServiceAttribute { get; } = $$"""
        // <auto-generated />
        
        #pragma warning disable
        #nullable enable
        
        namespace Ling.AutoInject
        {
            /// <summary>
            /// Marks a class for automatic registration as a transient service in the dependency injection container.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Ling.AutoInject.SourceGenerators", "{{Constants.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            [global::System.Diagnostics.Conditional("CODE_ANALYSIS")]
            internal sealed class TransientServiceAttribute : global::System.Attribute
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="TransientServiceAttribute"/> class.
                /// </summary>
                public TransientServiceAttribute()
                {
                }
        
                /// <summary>
                /// Initializes a new instance of the <see cref="TransientServiceAttribute"/> class with the specified service type.
                /// </summary>
                /// <param name="serviceType">The service type to register.</param>
                public TransientServiceAttribute(global::System.Type serviceType)
                {
                    ServiceType = serviceType;
                }
        
                /// <summary>
                /// Gets the service type to register.
                /// </summary>
                public global::System.Type? ServiceType { get; }
        
                /// <summary>
                /// Gets or sets the service key for keyed service registration.
                /// </summary>
                public object? ServiceKey { get; set; }

                /// <summary>
                /// Gets or sets a value indicating whether the generated registration should replace existing registrations for the service type.
                /// </summary>
                public bool Replace { get; set; }

                /// <summary>
                /// Gets or sets the strategy used to register the service.
                /// </summary>
                public ServiceRegistrationStrategy Strategy { get; set; } = ServiceRegistrationStrategy.TryAdd;

                /// <summary>
                /// Gets or sets a value indicating whether all implemented interfaces should be registered.
                /// </summary>
                public bool RegisterImplementedInterfaces { get; set; }
            }
        }
        """;
}
